### ISSUE TITLE
Wrong time PVOutput upload

### ISSUE THREAD

**Issue by Not2Fast** [ricott/sma.modbus#10]
Hi!
Since last weeks update, upload times to PVOutput are in CET instead of current CET+2. 
I’ve checked settings, but all seem correct. 
Any suggestions?
Thanks and best regards,
Arno

**Comment by Not2Fast** [comment]
PVoutput times are OK now!
_What's new in v2.3.1
Fixed timezone offset for PVO_utput_

**Comment by ricott** [comment]
Thanks @Not2Fast!
I had missed that I even had an issue here for this problem. Been too occupied with work as of late.

For completeness, this was the cause of the issue, https://github.com/athombv/homey-apps-sdk-issues/issues/169.
