### ISSUE TITLE
Can't connect my inverter

### ISSUE THREAD

**Issue by Crowntwig** [ricott/sma.modbus#15]
Hi! 
I recently got solar panels for my home and got the SMA Sunny Tripower Converter. Was happy to see that there was an SMA app for my Homey but I cannot link the two. I have checked that the port is the default one, 502, but Homey can't find my inverter. The IP-adress for it (I have tried every possibility) comes back as "incorrect". I have tried the IP adress stated when I log on to the inverters own WiFi, I have tried its IP-adress in my home wifi. Nothing works. At a loss here, would love some step by step help.

Martin

**Comment by ricott** [comment]
Hi!
At the end of the first post on the link, you have a guide on how to turn on Modbus for TCP, https://community.athom.com/t/app-pro-sma-solar-devices/696. 

Have you connected the inverter to your normal network via a cable or wifi? 
Can you from a laptop on the same network connect to the inverter? Not by using the inverters own wifi, but your normal wifi where your homey is also connected.
On a mac you can type `nc -vz <inverter ip> 502` (full example: `nc -vz 192.168.200.249 502`) and if it shows success you have connectivity from the network and your Homey should be able to connect.
From Windows, I guess you need [telnet](https://kb.synology.com/en-uk/DSM/tutorial/Whether_TCP_port_is_open_or_closed).
