### ISSUE TITLE
Some data to PVOutput missing in upload. (Since last update?)

### ISSUE THREAD

**Issue by Not2Fast** [ricott/sma.modbus#19]
Hi Robert,

Seems that since last update, upload to PVOutput.org is not complete anymore. 
Power is updated, but Energy, Efficiency, etc. is missing.
See screenshots:

<img width="712" alt="image" src="https://user-images.githubusercontent.com/84344702/152121576-83d0bdd9-92af-464a-b5a4-679438e1c889.png">

<img width="744" alt="image" src="https://user-images.githubusercontent.com/84344702/152121869-ab5f8465-6bd9-4b0e-ac39-a9b6ecf2227c.png">

<img width="663" alt="image" src="https://user-images.githubusercontent.com/84344702/152121728-81deae59-b9be-4d83-ae79-a4ca62c262cc.png">

Any idea?
Thanks!

**Comment by ricott** [comment]
I can observe the same thing myself, will have a look

![image](https://user-images.githubusercontent.com/31240726/152125327-7f9b6c2a-c374-4dbf-af9a-7f59bf46239a.png)

**Comment by ricott** [comment]
Just issued v2.3.4
A unit conversion problem, sent yield as kWh and not as Wh.

**Comment by Not2Fast** [comment]
Confirmed!

<img width="472" alt="image" src="https://user-images.githubusercontent.com/84344702/152146790-5bd45818-70d9-4a71-a753-71c0823d5fea.png">

Thanks for the quick support Robert!
