### ISSUE TITLE
Device Condition instead of Operational Status

### ISSUE THREAD

**Issue by SynoUser-NL** [ricott/sma.modbus#2]
Hi,

Again, thanks very much for modifying the app so I can add my SMA Inverter by specifying the IP address!
When using the app in Homey I found that I can monitor the operational status of the device, but I can not make a flow that triggers when the device condition is changed from OK to something else..
I'm not sure I can achieve the same thing by monitoring the operational status (MPP means nothing to me.. :) ) but it would make it a lot more clear for me if I could monitor on device condition. 
Would you by any chance be able to add this to your excellent app?

Thanks very much!
DenW

**Comment by ricott** [comment]
Hi,

Sure, that can be added. Will include it in the next release.
You can see possible status for both of the fields here, https://github.com/ricott/sma.modbus/blob/master/lib/decodeData.js. Look at decodeOperatingStatus and decodeConditionType.

/Richard

**Comment by ricott** [comment]
Released in version 2.0.4

**Comment by SynoUser-NL** [comment]
Thanks very much for your quick enhancement!
Much appreciated.. :)
