### ISSUE TITLE
SMA Sunny Tripower 8.0 only shows 1 phase.

### ISSUE THREAD

**Issue by Ch1msie** [ricott/sma.modbus#22]
Added today the SMA Sunny Tripower 8.0 inverter to homey. This is a 3 phase inverter, unfortunately Homey only shows 1 Phase, the L1. Is this a know bug?

![9F338561-C7C2-406A-A858-B593F56D721F](https://user-images.githubusercontent.com/104388626/165156540-c6d92b61-a9c8-4523-914d-2c04e640ce7a.jpeg)

**Comment by Ch1msie** [comment]
![CB8DDF38-DC7C-453A-B87B-683148A7A26B](https://user-images.githubusercontent.com/104388626/165364395-fd21e355-f109-4e8f-b7dd-db52f06fea63.jpeg)
![8F8C33BB-27FA-478B-B7F2-486C1EEC8889](https://user-images.githubusercontent.com/104388626/165364401-9714c7be-7732-4cf9-a4cc-b3636e2f069f.png)

**Comment by ricott** [comment]
Mainly interested in the device type property, but I guess it matches the name of your device, ie `STP 8.0-3AV-40`.
This inverter is for sure supported and only missing daily yield, which the app instead calculates manually for you.
I misunderstood your initial question though, the app only shows voltage for L1, even for 3-phase inverters. To limit the number of capabilities.

If you have an SMA Home Manager 2 it will show you the voltage of all three phases.

**Comment by ricott** [comment]
Got this request also from another user so decided to add L2 and L3. 
There is a test version 2.3.9, please try it out.
