### ISSUE TITLE
Spike on production

### ISSUE THREAD

**Issue by Moardeth** [ricott/sma.modbus#25]
At about 02:00 it spikes the production. At 01:55 daily is 56,37 kWh and at 01:59 it is 253,98 kWh and at 02:00 it is reset to 0 kWh.

Using a STP-10.0-3AV-40 SMA for my system with modbus.

Since im using power by the hour to calculate how much the system is producing it gives very very strange numbers ;) 

<img width="758" alt="Skärmbild 2023-04-17 145637" src="https://user-images.githubusercontent.com/119499681/232492240-327d6fa3-e624-4c21-a266-fd2367a28fb9.png">

**Comment by ricott** [comment]
Hmmm, checking again and now I see your Inverter model doesn't provide a daily yield, it is manually calculated by the app - so I assume there is a bug there then. Will check

**Comment by Moardeth** [comment]
Let me know if you need access or anything from my system! 👍

**Comment by ricott** [comment]
There is a new test version that should fix the reset, please try it out
https://homey.app/a/sma.modbus/test/

**Comment by Moardeth** [comment]
Nu gör det reset på rätt timme och hoppet är inte alls lika stort som innan. Innan såg det åt såhär.  Skickat från min iPhone11 maj 2023 kl. 17:11 skrev Richard Barkestam ***@***.***>:﻿
There is a new test version that should fix the reset, please try it out
https://homey.app/a/sma.modbus/test/

**Comment by Moardeth** [comment]
This is how it looks with latest test version
![image1](https://github.com/ricott/sma.modbus/assets/119499681/2906b9ff-f05d-4565-97f6-c526b4718d9d)
![image1_Zoom](https://github.com/ricott/sma.modbus/assets/119499681/2e76c3ed-6304-444b-8701-f206a693b903)

This is before 
![image2](https://github.com/ricott/sma.modbus/assets/119499681/a1f92406-2986-4448-bdd0-fb70a3b42ea8)

**Comment by Moardeth** [comment]
The small spike now is probably a grafical error when viewing on the phone. 
23:58 - 54.88 kWh
23:59 - 50.31 kWh
24:00 - 0.00 kWh

When reading the values with mouse over on computer.

**Comment by ricott** [comment]
You can download the data in the graph. Should be easier to see the actual values.
<img width="473" alt="image" src="https://github.com/ricott/sma.modbus/assets/31240726/7289b773-a9b5-4a19-a4e3-d95a0ef4124d">

**Comment by Moardeth** [comment]
Almost always use the app so haven't seen that option ;) 

With latest update on 2.4.6 - test/experimental 👌
2023-05-12T21:50:00.000Z,70.48000000000002
2023-05-12T21:55:00.000Z,70.48000000000002
2023-05-12T22:00:00.000Z,0
2023-05-12T22:05:00.000Z,0
Total reset! Nice work

Homey doesn't handle timezones verywell so the time is off but 🤣


Thanks for your work with the app! Sending a small donation and hope everyone who uses your app does the same.

**Comment by ricott** [comment]
Thanks 🙏
