### ISSUE TITLE
Support for SMA Sunny Tripower 10.0 SE

### ISSUE THREAD

**Issue by TimmyT68** [ricott/sma.modbus#26]
Hello,

I have a Sunny Tripower 10.0 SE Inverter. And all the values are not correct reportet. The battery and the loading value  are totally not reportet.
Will you support this inverter?

Best regards
TimmyT68

**Comment by ricott** [comment]
Hi!

There is a new test version, https://homey.app/a/sma.modbus/test/
I quickly enabled the recognition of the SE hybrid inverters, you should add it as an inverter device.
Won't show any battery info as of yet, but you should see all PV capabilities.

**Comment by TimmyT68** [comment]
Hi,thank you. This version works fine for me. Did you support the battery in a future version also?Best regards ThomasAm 28.06.2023 um 22:56 schrieb Richard Barkestam ***@***.***>:﻿
Hi!
There is a new test version, https://homey.app/a/sma.modbus/test/
I quickly enabled the recognition of the SE hybrid inverters, you should add it as an inverter device.
Won't show any battery info as of yet, but you should see all PV capabilities.

**Comment by ricott** [comment]
Should be able to easily add more capabilities for these hybrid inverters 👍
Question is what properties are most interesting?

**Comment by TimmyT68** [comment]
Hi,

I think some information about the battery conditions is interesting.

For example the actual state of charge in percent, the actual charging or decharging in W for the beginning.

Best regards
Thomas

**Comment by ricott** [comment]
https://community.homey.app/t/app-pro-sma-solar-devices/696/318
