### ISSUE TITLE
SMA TRIPOWER 6.0 does not seem to be accepted.

### ISSUE THREAD

**Issue by EBlom71** [ricott/sma.modbus#28]
My SMA SUNNY TRIPOWER 6.0 cannot be added to Homey.

It comes with the following response:

![image](https://github.com/ricott/sma.modbus/assets/138625073/904bc661-a74b-4441-a004-9adc43fc391c)

I am sure the IP address as well as the port is correct.

**Comment by ricott** [comment]
You have enabled modbus on the inverter as per instructions [here](https://community.homey.app/t/app-pro-sma-solar-devices/696#enable-modbus-in-your-inverterstorage-product-9)?

**Comment by EBlom71** [comment]
Thank you Richard, now it works!Met vriendelijke groet, Erwin BlomVan: Richard Barkestam ***@***.***>Verstuurd: woensdag, juli 5, 2023 8:01:12 a.m.Aan: ricott/sma.modbus ***@***.***>CC: EBlom71 ***@***.***>; Author ***@***.***>Onderwerp: Re: [ricott/sma.modbus] SMA TRIPOWER 6.0 does not seem to be accepted. (Issue #28)
You have enabled modbus on the inverter as per instructions here?
