### ISSUE TITLE
Daily production

### ISSUE THREAD

**Issue by mvaneck83** [ricott/sma.modbus#3]
Ey, 
What happened with the daily production read out? I used it in a flow but it isn't available anymore. 

Thanks for a reply,
Martijn

**Comment by ricott** [comment]
Hi,

When did you see it went missing, I guess in first v2 release? 
What is the device type in the advanced setting on your inverter? Since version 2 uses custom mapping per inverter type I can't look at this without knowing which device type it is. 

/Richard

**Comment by mvaneck83** [comment]
EY Richard,
Thanks for quick reply. Last week I noticed it for the first time. So I think that it is since version 2 yes. I have a sma sunny boy 3.0-1av-40. In advanced settings I see “UNKOWN (9319)” as type and serial number “1992108605”. See photo attachment 
![B7D0B72E-14E7-4CDB-B533-1849325139EE](https://user-images.githubusercontent.com/52035955/70088260-2ee3e400-1616-11ea-98d3-042066d918da.png)

**Comment by ricott** [comment]
Thanks, '9319' gave me everything I needed. Support for all capabilities will come in the next release. Traveling this week so releasing next week.

**Comment by mvaneck83** [comment]
You’re the man!

kind regards,

Martijn van Eck
