### ISSUE TITLE
SMA Inverter Battery 

### ISSUE THREAD

**Issue by MikeRow1972** [ricott/sma.modbus#30]
I will create a flow and use Inverter Cart "Battery charge changed to%" but the input field is missing.

Is this a fail on my side or on the card.

I use Homey pro 2023

![image](https://github.com/ricott/sma.modbus/assets/116517462/90f1d9f7-1dff-407d-bb09-030c9a56eac8)

**Comment by ricott** [comment]
Currently on a trip so cant check much. But is this the sunny boy device type or do you have the new smart energy hybrid inverter?

**Comment by MikeRow1972** [comment]
Hello Richard, no problem. It’s a SMA SBS 3.7-10

Regards Mike

Von: Richard Barkestam ***@***.***>
Gesendet: Donnerstag, 13. Juli 2023 09:45
An: ricott/sma.modbus ***@***.***>
Cc: MikeRow1972 ***@***.***>; Author ***@***.***>
Betreff: Re: [ricott/sma.modbus] SMA Inverter Battery (Issue #30)


Currently on a trip so cant check much. But is this the sunny boy device type or do you have the new smart energy hybrid inverter?

**Comment by MikeRow1972** [comment]
device details i can see 
![image](https://github.com/ricott/sma.modbus/assets/116517462/00780341-3196-4701-8e9f-4c27aa773b54)

**Comment by MikeRow1972** [comment]
Hello Richard, any news about my problem? 

best regards Mike

**Comment by ricott** [comment]
Came back home yesterday, so not been able to spend a lot of time yet :)

You have a sunny boy storage from what I can tell. 
I added support for the new hybrid inverters in the inverter device type recently, and I'm considering adding sunny boy storage support there as well - to phase out the storage device type.

Since I don't have a sunny boy unit it is a little problematic with testing. Can you share the values you see in addition to the ones you already shared.

**Comment by MikeRow1972** [comment]
Hi Richard, I'm a Homey newbie but I work in the IT industry. I think you can guide me through the system for troubleshooting.
In the device properties I see the following values + Battery SOC

![image](https://github.com/ricott/sma.modbus/assets/116517462/e9eca6ad-77e0-434e-b4e7-68b779a7b0f6)

and following cards 
![image](https://github.com/ricott/sma.modbus/assets/116517462/4dcf484d-734d-4a04-99d4-7624bd00699e)
![image](https://github.com/ricott/sma.modbus/assets/116517462/7984e631-e3bf-47df-9d07-05dabec8da3c)

This when Cards has no input fields

![image](https://github.com/ricott/sma.modbus/assets/116517462/d5946029-24e3-4821-bbb6-7ed992c2aa56)

Is that what you need from me?

**Comment by ricott** [comment]
Thanks for the screen shots

As for the support for hybrid/battery inverters in the normal inverter device type;
- I have combined charge and discharge into one capability for the hybrid inverters, value is negative for discharge.
- Battery state of charge is using the Homey built in battery capability, shown on a separate tab.
- I have just added the battery operational status, not released yet.

The capabilities I'm interested in are these. 
- power drawn
Not sure what this actually shows? Different from discharge?
- power grid feedin
My thinking is that any grid values require an energy meter or home manager and these values are available in that device
- battery capacity
What is battery capacity vs state of charge (SOC)? Both value are in % as per the spec.

**Comment by MikeRow1972** [comment]
power drawn
Not sure what this actually shows? Different from discharge?

the value is correct, battery is full 
![image](https://github.com/ricott/sma.modbus/assets/116517462/42611938-3f86-43a5-81ba-904b0522d00a)

power grid feedin
My thinking is that any grid values require an energy meter or home manager and these values are available in that device

the value is correct 
![image](https://github.com/ricott/sma.modbus/assets/116517462/dfdf01c4-f747-4a02-bd5f-df875531231d)



battery capacity
What is battery capacity vs state of charge (SOC)? Both value are in % as per the spec.
values are correct 
capacity 96%
state of charge 100% 

![image](https://github.com/ricott/sma.modbus/assets/116517462/8eb08e44-809a-4013-90fb-00c4ea285a9d)

Do you know why the input fields from Flow cards missing??

**Comment by ricott** [comment]
You can now try the new [test version](https://homey.app/a/sma.modbus/test/)
Add the Sunny Boy Storage as an `inverter` device type, not `storage` device type.

**Comment by MikeRow1972** [comment]
Hello Richard, sounds good. 
![image](https://github.com/ricott/sma.modbus/assets/116517462/f1e3bbc3-3a57-4edf-adc7-8000d26f65cd)
![image](https://github.com/ricott/sma.modbus/assets/116517462/80c58aa5-c16d-4ee6-be33-2d058585eb82)
![image](https://github.com/ricott/sma.modbus/assets/116517462/3dce5851-0c88-4f14-abd4-85c51119391c)
