### ISSUE TITLE
Missing Inverter with Bluetooth interface

### ISSUE THREAD

**Issue by Homey4Osty** [ricott/sma.modbus#32]
Hello,
I'm having an "old" Inverter (Sunny Boy SB 5000TL-20) with a Bluetooth interface. This interface is for the communication with my Sunny Beam (Typ BEAM-BT.GR1). It's only possible to get a monitoring with a running computer. And i won't do that.

Now i found your SMA Energy App at the homey store. But it doesn't support Bluetooth inverter. Right?

Is it possible to add the Bluetooth interface and my inverter? I want to get a monitoring with Homey (Pro 2023).

Thanks a lot!

Greatings Osty

**Comment by ricott** [comment]
Hi!

I have gotten this request once before, but unfortunately nothing in scope for this app at the moment. The bluetooth implementation would be very different from the modbus implementation that is there today. I lack that knowledge and time to invest currently.
