### ISSUE TITLE
SMA Wallbox / Inverter

### ISSUE THREAD

**Issue by meinerseins** [ricott/sma.modbus#34]
Hello, I only get the manager installed. The inverter or the wallbox appears as an error (wrong port or IP)
[Image-24.png.pdf](https://github.com/ricott/sma.modbus/files/13511521/Image-24.png.pdf)
Can you help me ?

**Comment by ricott** [comment]
Hi!

Did you enable modbus in your inverter? It is disabled by default
https://community.homey.app/t/app-pro-sma-solar-devices/696#enable-modbus-in-your-inverterstorage-product-9
