### ISSUE TITLE
Support for SMA Core1

### ISSUE THREAD

**Issue by BerjanR** [ricott/sma.modbus#36]
Is it possible to ad support for the SMA core 1 inverter? its connects with homey but the daily yield isnt there in the output to pv output. My other inverter works fine.

**Comment by ricott** [comment]
Sure, try it out in the latest [test version](https://homey.app/a/sma.modbus/test/).
Please remove the old device and re-add it to make sure it gets the correct type.

**Comment by BerjanR** [comment]
still not recognized with 2.5.9.

**Comment by ricott** [comment]
What does it say as the device type on the settings of the device, after you re-added it?

**Comment by BerjanR** [comment]
Soort apparaat
UNKNOWN (9338)
Serienummer
3008800825
Software versie
unknown
Max vermogen (W)
50000
Grid country standard
unknown
Daily yield manually calculated
false

**Comment by ricott** [comment]
Then it makes sense there is no difference 👍
Device id `9338` is not mentioned in SMAs Modbus docs for the CORE1 inverters.

<img width="1733" alt="image" src="https://github.com/ricott/sma.modbus/assets/31240726/76a6a15e-ffb3-4422-b4cb-c3a1167dd8c6">

**Comment by BerjanR** [comment]
ah, its a stp 50-40

**Comment by ricott** [comment]
That explains it! I guess older model, and thus not even visable on SMAs site via product page.
Now it should be there in v2.6.0

**Comment by BerjanR** [comment]
It works! nice :) many thanks
