### ISSUE TITLE
STP5000L-20: no option to enable Modbus TCP Server

### ISSUE THREAD

**Issue by giggo** [ricott/sma.modbus#5]
I don't have an option for my STP5000L-20 to enable "Modbus TCP Server" in "external communications" section of Sunny Explorer. Any idea if something else needs to be enabled first?

**Comment by ricott** [comment]
Quickly checked the inverter and it seems to support modbus.
Is this the problem you have? That you are not logged in as installer properly?
https://community.athom.com/t/app-sma-solar-devices/696/27

**Comment by giggo** [comment]
I needed a firmware update to enable Modbus. Works very well now. Thanks
